### ISSUE TITLE
Crashes on Mac without debugger attached

### ISSUE THREAD

**Issue by ojwoodford** [scottt/debugbreak#11]
When compiled on an X64 Mac using Xcode 7.3, programs with the debugger attached stop at debug_break() as expected. However, without a debugger attached the program crashes at debug_break().

**Comment by Snaipe** [comment]
Well, this is actually expected behaviour. Think of it as an abort() that traps.

**Comment by scottt** [comment]
Yeah, @ojwoodford , I agree with @Snaipe. The existing behavior of generating a  `SIGTRAP` and terminating the process by default matches the intuition of developers who know `debug_break()` is just inserting an `int 3` (x86) for `bkpt` (ARM) instruction in the instruction stream. It also matches the behavior of the  `__debugbreak()` intrinsic on Visual C++ and Windows.

Your desire to leave `debug_break()` calls in the code and have them act as `nops` could be accomplished by wrapping `debug_break()` calls in a macro that changes the behavior based on whether you're doing a Debug or Release build.

Also, if the "interesting" points in your code seem fairly stable, consider using [User Space Static Probes](https://sourceware.org/systemtap/wiki/AddingUserSpaceProbingToApps). These work well on both OSX with Dtrace and Linux on Linux through GDB, SystemTap etc.

**Comment by ojwoodford** [comment]
I wasn't expecting this behaviour. The Readme clearly states that debug_break():

> "Works like the DebugBreak() fuction provided by Windows".

Having used __debugbreak() on Windows a great deal, I'm fairly certain that it is ignored if a debugger is not attached. This also ties in with the description [here](https://msdn.microsoft.com/en-us/library/ea9yy3ey.aspx): 

> "DebugBreak and __debugbreak have the same effect as setting a breakpoint at that location."

I'm already using your suggestion of only using debug_break() in Debug builds. However, just because I'm using a Debug build doesn't mean I have a debugger attached.

I've also tried wrapping debug_break() in a try/catch, but this doesn't work.

**Comment by Snaipe** [comment]
> Having used __debugbreak() on Windows a great deal, I'm fairly certain that it is ignored if a debugger is not attached.

I fired my windows VM to check this statement, and it's definitely not ignored. The following program:

```c
#include <stdio.h>

int main(void) {
	__debugbreak();
	puts("Hello world");
	return 0;
}
```

crashes before reaching the "Hello World" in both Release & Debug build modes.

It is common practice however to wrap the __debugbreak with IsDebuggerPresent, so I'm guessing that you had a `#define __debugbreak() if (IsDebuggerPresent()) __debugbreak()` somewhere.

**Comment by ojwoodford** [comment]
@Snaipe Thanks for checking. I assume you were compiling with MSVC? I'll test my Windows code when I'm back at my PC to see how it was working in my case. Very strange that the docs don't mention an abort being signalled for __debugbreak() though.

**Comment by Snaipe** [comment]
> I assume you were compiling with MSVC?

Yes. The sample above was compiled with MSVC 14, shipped with Visual Studio 2015.

> Very strange that the docs don't mention an abort being signalled for __debugbreak() though.

The documentation says so implicitely, I'm afraid: https://msdn.microsoft.com/en-us/library/f408b4et.aspx

__debugbreak is equivalent to int 3, which raises a structured exception on Windows (& a signal on unices).

Regarding your original issue, you could also on OS X probe if a debugger is attached, à la IsDebuggerPresent, with something like `ptrace(PTRACE_TRACEME, 0, 0, 0);`. There is sadly no portable universal solution though.

**Comment by ojwoodford** [comment]
This looks useful:
https://developer.apple.com/library/mac/qa/qa1361/_index.html
