### ISSUE TITLE
Include guard is dysfunctional.

### ISSUE THREAD

**Issue by nkolotov** [scottt/debugbreak#16]
[`DEBUG_BREAK_H` macro is used as an include guard](https://github.com/scottt/debugbreak/blob/5d620814b1a240bbdf50c1dceed1eaf5a3fefce8/debugbreak.h#L26) but it is not defined anywhere in the header causing multiple inclusions of `debugbreak.h` into a single translation unit to produce redefinition errors.

**Comment by scottt** [comment]
Thanks for noticing and fixing this.
