### ISSUE TITLE
Warning message using clang 10

### ISSUE THREAD

**Issue by ferranferri** [scottt/debugbreak#18]
I'm getting the warning:

> warning: 'gnu_inline' attribute without 'extern' in C++ treated as externally available, this changed in Clang 10 [-Wgnu-inline-cpp-without-extern]

The code (lines 128-129):

```
__attribute__((gnu_inline, always_inline))
__inline__ static void debug_break(void)
```

**Comment by scottt** [comment]
Fixed this by removing the `gnu_inline` function attribute. I verified the warning no longer happens with clang++ 11.0.1
