### ISSUE TITLE
Doesn't compile on Atollic 5.0.0

### ISSUE THREAD

**Issue by marklakata** [scottt/debugbreak#3]
# include <sys/syscall.h>

is not needed on embedded systems -- since it doesn't exist! Perhaps this include should be conditional.

I'm using Atollic 5.0 (This is an ARM Cortex M3)

**Comment by scottt** [comment]
I believe this is fixed. I've not tested with the Atollic toolchain but have tested debugbreak.h with the [GNU ARM Embedded Toolchain](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm) on Cortex-M.
