### ISSUE TITLE
What about ARM's BKPT?

### ISSUE THREAD

**Issue by JodiTheTigger** [scottt/debugbreak#8]
Is it viable for making a breakpoint? If so, does it solve the gdb issue?

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0552a/BABHCHGB.html

**Comment by scottt** [comment]
I've been successfully using `debugbreak.h` on  ARM Cortex-M targets for a while now.
It generates a `.inst 0xde01`  instruction, which shows up as:
```
01 de	udf	#1
```
in the disassembly.
